name: Build hel-Qogir-theme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Fix Pacman and Install Deps
        run: |
          sed -i '/\[extra\]/,/Include/s/^#//' /etc/pacman.conf
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sassc gtk-engine-murrine gtk-engines

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Package
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder .
          sudo -u builder makepkg -f --noconfirm

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hel-Qogir-theme-zst
          path: "*.pkg.tar.zst"
