name: Build hel-Qogir-theme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install Build Tools Only
        run: |
          pacman -Syu --noconfirm
          # هنثبت بس اللي محتاجينه عشان "نصنع" الملف
          pacman -S --noconfirm base-devel git sassc 

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Package
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder .
          # علم --nodeps بيخلي السيرفر يطنش إن murrine مش عنده، 
          # لأننا كدة كدة بنبني CSS مش بنشغل واجهة
          sudo -u builder makepkg -f --noconfirm --nodeps

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hel-Qogir-theme-zst
          path: "*.pkg.tar.zst"
