name: Build hel-Qogir-theme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install Tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sassc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Package
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          
          # البحث عن الملفات ونسخها لمجلد builder لضمان وجودها
          find . -name "PKGBUILD" -exec cp {} /home/builder/ \;
          find . -name "_colors.scss" -exec cp {} /home/builder/ \;
          find . -name "_variables.scss" -exec cp {} /home/builder/ \;
          
          chown -R builder:builder /home/builder/
          cd /home/builder/
          
          # البناء بصيغة zst وتخطي التبعات المفقودة في السيرفر
          sudo -u builder makepkg -f --noconfirm --nodeps
          
          # نقل الحزمة الناتجة لمجلد العمل الرئيسي للرفع
          cp *.pkg.tar.zst $GITHUB_WORKSPACE/

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hel-Qogir-theme-zst
          path: "*.pkg.tar.zst"
