name: Build Hel-Qogir-Theme ZST
on: [push]

jobs:
  build_zst:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Update System and Install Build Tools
        run: |
          # تحديث القاعدة وتثبيت أدوات البناء الأساسية فقط
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sassc

      - name: Checkout Your Files
        uses: actions/checkout@v4

      - name: Build Package (makepkg)
        run: |
          useradd -m builder
          # إعطاء صلاحيات للمستخدم الجديد
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder .
          # استخدام --ignorearch و --nodeps لضمان البناء داخل الحاوية بدون مشاكل توافقية
          sudo -u builder makepkg -f --noconfirm --nodeps

      - name: Upload ZST Package
        uses: actions/upload-artifact@v4
        with:
          name: hel-Qogir-theme-zst
          path: "*.pkg.tar.zst"
