name: Build hel-Qogir-theme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install Build Tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sassc

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Package
        run: |
          # 1. إعداد المستخدم
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          
          # 2. نسخ الملفات باستخدام المسار المطلق لضمان عدم ضياعها
          # $GITHUB_WORKSPACE هو المكان اللي الأكشن نزل فيه ملفاتك
          cp $GITHUB_WORKSPACE/PKGBUILD /home/builder/
          cp $GITHUB_WORKSPACE/_colors.scss /home/builder/
          cp $GITHUB_WORKSPACE/_variables.scss /home/builder/
          
          # 3. ضبط الصلاحيات
          chown -R builder:builder /home/builder/
          
          # 4. البناء من مجلد الهوم الخاص بالبيلدر
          cd /home/builder/
          # --nodeps عشان نتخطى فحص التبعات في السيرفر ونعتمد على hpm عند المستخدم
          sudo -u builder makepkg -f --noconfirm --nodeps
          
          # 5. نقل ملف الـ zst الناتج لمكان الأكشن عشان يقدر يرفعه
          cp *.pkg.tar.zst $GITHUB_WORKSPACE/

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hel-Qogir-theme-zst
          path: "*.pkg.tar.zst"
